### ISSUE TITLE
Tether Extension

### ISSUE THREAD

**Issue by pdjbarber** [gnoshme/tog#1]
I am not sure where i am going wrong, i have a tether script working with no issues.. infact it is an adapted version of your ktether :)

however when i try to install the extention i get the error:-

------------------------------------------------------------
Installing Extension :: tether
------------------------------------------------------------
Traceback (most recent call last):
	25: from ./tog:40:in `<main>'
	24: from /home/patrick/tog/lib/mods.rb:121:in `load_mod_actions'
	23: from /home/patrick/tog/lib/mods.rb:147:in `load_mods'
	22: from /home/patrick/tog/lib/mods.rb:147:in `each'
	21: from /home/patrick/tog/lib/mods.rb:148:in `block in load_mods'
	20: from /home/patrick/tog/lib/mods.rb:148:in `load'
	19: from /home/patrick/tog/modules/core/core-actions.rb:58:in `<top (required)>'
	18: from /home/patrick/tog/lib/mods.rb:74:in `installmod'
	17: from /home/patrick/tog/lib/mods.rb:140:in `load_mod'
	16: from /home/patrick/tog/lib/mods.rb:140:in `load'
	15: from /home/patrick/tog/modules/extensions/tether-lib.rb:3:in `<top (required)>'
	14: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	13: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	12: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	11: from /var/lib/gems/2.5.0/gems/ffi-gphoto2-0.7.1/lib/gphoto2.rb:3:in `<top (required)>'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /var/lib/gems/2.5.0/gems/ffi-gphoto2-0.7.1/lib/ffi/gphoto2.rb:2:in `<top (required)>'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /var/lib/gems/2.5.0/gems/ffi-gphoto2-0.7.1/lib/ffi/gphoto2_port.rb:3:in `<top (required)>'
	 4: from /var/lib/gems/2.5.0/gems/ffi-gphoto2-0.7.1/lib/ffi/gphoto2_port.rb:4:in `<module:FFI>'
	 3: from /var/lib/gems/2.5.0/gems/ffi-gphoto2-0.7.1/lib/ffi/gphoto2_port.rb:7:in `<module:GPhoto2Port>'
	 2: from /var/lib/gems/2.5.0/gems/ffi-1.9.25/lib/ffi/library.rb:99:in `ffi_lib'
	 1: from /var/lib/gems/2.5.0/gems/ffi-1.9.25/lib/ffi/library.rb:99:in `map'
/var/lib/gems/2.5.0/gems/ffi-1.9.25/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'libgphoto2_port': /usr/lib/x86_64-linux-gnu/libgphoto2_port: cannot read file data: Is a directory. (LoadError)
Could not open library 'libgphoto2_port.so': libgphoto2_port.so: cannot open shared object file: No such file or directory

I am using the latest git version (cloned 5 mins ago) previous versions also had same errors

any suggestions/guidance would be appreciated

**Comment by gnoshme** [comment]
Doh!  Just found this using google, ironically trying to get my new machine up and running with my own damn tool!  Looks like the gem photo2 has some dependencies. You need to apt-get install gphoto2 and  apt-get install libgphoto2-dev
